Repository kyma-incubator/kyma-showcase, pull requests merged in 2021-09, with the labels that each got.

#75 Hotfix
  backend/cmd/main.go
Labels: size/XS, lgtm, ✨ hotfix ✨

#71 Naming convention in backend
  backend/internal/api/handler.go
  backend/internal/api/handler_test.go
  backend/internal/api/mocks/DBManager.go
  backend/internal/database/database.go
  backend/internal/database/database_test.go
  backend/internal/events/event_test.go
Labels: size/L, lgtm, ⚙️ refactor/QOL

#78 Fetch image details
  frontend/src/assets/styles/style.js
  frontend/src/views/ImageDetailsPage/ImageDetailsPage.js
  frontend/src/views/ImageDetailsPage/components/ImageDetails/ImageDetails.js
  frontend/src/views/ImageDetailsPage/components/ImageDetails/ImageDetails.styles.js
  frontend/src/views/ImageDetailsPage/components/ImageDetailsArea/ImageDetailsArea.js
Labels: enhancement, size/L, lgtm

#77 Font-processing function
  resources/functions/font-processing.yaml
  resources/functions/image-processing.yaml
  resources/subscriptions/font-processing-subscription.yaml
Labels: enhancement, size/L, lgtm

#79 Handwriting lambda
  resources/functions/handwriting-processing.yaml
  resources/functions/image-processing.yaml
  resources/subscriptions/handwriting-processing-subscription.yaml
Labels: enhancement, size/L, lgtm

#80 Logo lambda
  resources/functions/image-processing.yaml
  resources/functions/logo-processing.yaml
  resources/subscriptions/logo-processing-subscription.yaml
Labels: enhancement, size/L, lgtm

#81 Hotfix
  resources/functions/handwriting-processing.yaml
Labels: size/XS, lgtm, ✨ hotfix ✨

#76 Adding API endpoint with PUT
  RESTAPI_contract.md
  backend/cmd/main.go
  backend/internal/api/handler.go
  backend/internal/api/handler_test.go
  backend/internal/api/mocks/DBManager.go
  backend/internal/api/mocks/EventBus.go
  backend/internal/api/mocks/IdGenerator.go
  backend/internal/database/database.go
  backend/internal/model/model.go
Labels: enhancement, size/XL, lgtm

#84 Rename all yaml files
  resources/functions/labels-handwriting.yaml
  resources/functions/labels-logo.yaml
  resources/functions/labels-text.yaml
  resources/functions/labels.yaml
  resources/functions/objects.yaml
  resources/subscriptions/labels-handwriting-sub.yaml
  resources/subscriptions/labels-logo-sub.yaml
  resources/subscriptions/labels-sub.yaml
  resources/subscriptions/labels-text-sub.yaml
  resources/subscriptions/objects-sub.yaml
Labels: size/M, lgtm, ⚙️ refactor/QOL

#85 Hotfix
  resources/functions/labels-logo.yaml
  resources/functions/labels-text.yaml
Labels: size/S, lgtm, ✨ hotfix ✨, 😡 friday PR 🤬

#86 Add face processing lambda
  resources/functions/faces.yaml
  resources/subscriptions/faces-sub.yaml
Labels: enhancement, size/L, lgtm, 😡 friday PR 🤬

#87 Display detected text
  frontend/src/views/HomePage/components/ImagesSection/ImagesSection.js
  frontend/src/views/ImageDetailsPage/ImageDetailsPage.js
  frontend/src/views/ImageDetailsPage/components/ImageDetails/ImageDetails.js
  frontend/src/views/ImageDetailsPage/components/ImageDetails/ImageDetails.styles.js
  frontend/src/views/ImageDetailsPage/components/ImageDetailsArea/ImageDetailsArea.js
Labels: enhancement, size/M, lgtm, 😡 friday PR 🤬

#88 Landmarks lambda
  resources/functions/landmarks.yaml
  resources/subscriptions/landmarks-subscription.yaml
Labels: enhancement, size/L, lgtm, 😡 friday PR 🤬

#92 Face detection hotfix
  resources/functions/faces.yaml
Labels: size/S, lgtm, ✨ hotfix ✨

#93 fix logo detection
  resources/functions/labels-logo.yaml
Labels: size/XS, lgtm

#94 Face details processing lambda triggered by object lambda
  resources/functions/objects-faces.yaml
  resources/functions/objects.yaml
  resources/subscriptions/objects-faces-sub.yaml
Labels: enhancement, size/M, lgtm

#90 Create secret yaml file
  README.md
  resources/secrets.yaml
Labels: enhancement, size/S, lgtm

#95 Display full img's description
  frontend/src/assets/styles/style.js
  frontend/src/views/ImageDetailsPage/components/FeatureTiles/FaceTile/FaceTile.js
  frontend/src/views/ImageDetailsPage/components/FeatureTiles/FeatureTile/FeatureTile.js
  frontend/src/views/ImageDetailsPage/components/FeatureTiles/LandmarksTile/LandmarksTile.js
  frontend/src/views/ImageDetailsPage/components/FeatureTiles/LandmarksTile/LandmarksTile.styles.js
  frontend/src/views/ImageDetailsPage/components/FeatureTiles/TextTile/TextTile.js
  frontend/src/views/ImageDetailsPage/components/ImageDetails/ImageDetails.js
  frontend/src/views/ImageDetailsPage/components/ImageDetails/ImageDetails.styles.js
Labels: enhancement, size/L, lgtm

#96 Fix import in FaceTile component
  frontend/src/views/ImageDetailsPage/components/FeatureTiles/FaceTile/FaceTile.js
Labels: size/XS, lgtm, ✨ hotfix ✨

#101 Created Entity and Category processing lambda
  resources/functions/labels-text.yaml
  resources/functions/text-category.yaml
  resources/functions/text-entity.yaml
  resources/subscriptions/text-category.yaml
  resources/subscriptions/text-entity-sub.yaml
Labels: enhancement, size/L, lgtm

#110 Add coment information in code
  resources/functions/labels-handwriting.yaml
  resources/functions/labels-logo.yaml
  resources/functions/objects-faces.yaml
Labels: size/XS, lgtm, ✨ hotfix ✨

#112 Update README.md
  README.md
Labels: size/XS, lgtm

#113 Sentiment analysis function
  resources/functions/text-sentiment.yaml
  resources/subscriptions/landmarks-sub.yaml
  resources/subscriptions/text-category-sub.yaml
  resources/subscriptions/text-sentiment-sub.yaml
Labels: enhancement, size/L, lgtm

#118 Redirect to errorpage on bad image id
  frontend/package-lock.json
  frontend/src/views/ImageDetailsPage/ImageDetailsPage.js
Labels: enhancement, size/S, lgtm

#119 HOTFIX
  resources/functions/text-category.yaml
Labels: size/XS, lgtm, ✨ hotfix ✨

#120 Displaying information about the image
  frontend/src/views/ImageDetailsPage/ImageDetailsPage.js
  frontend/src/views/ImageDetailsPage/components/FeatureTiles/TextCategoryTile/TextCategoryTile.js
  frontend/src/views/ImageDetailsPage/components/FeatureTiles/TextDocSentimentTile/TextDocSentimentTile.js
  frontend/src/views/ImageDetailsPage/components/FeatureTiles/TextEntityTile/TextEntityTile.js
  frontend/src/views/ImageDetailsPage/components/FeatureTiles/TextSentenceSentimentTile/TextSentenceSentimentTile.js
  frontend/src/views/ImageDetailsPage/components/ImageDetails/ImageDetails.js
  resources/functions/text-sentiment.yaml
Labels: enhancement, size/L, lgtm

#109 Sort images by date in feed
  frontend/src/contexts/imagesContext.js
  frontend/src/views/HomePage/components/ImagesSection/ImagesSection.js
Labels: enhancement, size/XS, lgtm

#121 Add basic makefile
  backend/Dockerfile
  backend/Makefile
  common_makefile.mk
  frontend/Makefile
Labels: size/M, lgtm

#122 Fix formatting
  backend/internal/api/handler.go
Labels: size/XS, lgtm

#123 Fix choosing the same photo to upload
  frontend/src/views/HomePage/components/UploadImage/UploadImage.js
Labels: size/XS, lgtm, ⚙️ refactor/QOL

#126 Add event URL to env
  resources/functions/labels-text.yaml
Labels: bug, size/XS, lgtm, ✨ hotfix ✨

#127 Calculating sentiment
  frontend/src/views/ImageDetailsPage/components/FeatureTiles/TextDocSentimentTile/TextDocSentimentTile.js
  frontend/src/views/ImageDetailsPage/components/FeatureTiles/TextSentenceSentimentTile/TextSentenceSentimentTile.js
  resources/functions/text-entity.yaml
  resources/functions/text-sentiment.yaml
Labels: enhancement, size/L, lgtm

#129 Fix info in footer
  frontend/src/components/Footer/Footer.js
Labels: bug, size/XS, lgtm, ✨ hotfix ✨

#128 Prow configuration
  backend/Dockerfile
  backend/Makefile
Labels: enhancement, size/S, lgtm

#116 Functions use internal url to communicate with backend
  resources/backend/apirule.yaml
  resources/functions/functions-config.yaml
  resources/functions/labels-handwriting.yaml
  resources/functions/labels-logo.yaml
  resources/functions/labels-text.yaml
  resources/functions/labels.yaml
  resources/functions/landmarks.yaml
  resources/functions/objects-faces.yaml
  resources/functions/objects.yaml
  resources/functions/text-category.yaml
  resources/functions/text-entity.yaml
Labels: size/M, lgtm, 😡 friday PR 🤬, ⚙️ refactor/QOL

#131 Accepting URL as image
  frontend/src/views/HomePage/components/UploadImage/UploadImage.js
  frontend/src/views/HomePage/components/UploadImage/UploadImage.styles.js
  frontend/src/views/ImageDetailsPage/components/ImageDetailsArea/ImageDetailsArea.js
Labels: enhancement, size/L, lgtm

#130 Updating documentation
  README.md
  docs/README.md
  docs/architecture.md
  docs/assets/diagram_showcase.svg
  docs/details.md
  docs/development.md
Labels: documentation, size/L, lgtm

#135 Change text-sentiment config
  resources/functions/text-sentiment.yaml
Labels: size/XS, lgtm, ✨ hotfix ✨

#136 Added logo
  README.md
  docs/assets/logo.png
Labels: size/XS, lgtm

#132 Accepting URL as an image on backend
  backend/go.mod
  backend/go.sum
  backend/internal/api/handler.go
  backend/internal/api/handler_test.go
Labels: enhancement, size/L, lgtm

#115 Checking if content exists when posting to database
  backend/go.mod
  backend/go.sum
  backend/internal/api/handler.go
  backend/internal/api/handler_test.go
Labels: size/M, lgtm, 😡 friday PR 🤬, ⚙️ refactor/QOL

#133 Modify UI design
  frontend/public/img/KymaLogo.png
  frontend/src/assets/styles/GlobalStyle.js
  frontend/src/assets/styles/style.js
  frontend/src/components/ErrorPage/ErrorPage.js
  frontend/src/components/ErrorPage/ErrorPage.styles.js
  frontend/src/components/Footer/Footer.js
  frontend/src/components/Footer/Footer.styles.js
  frontend/src/components/Header/Header.js
  frontend/src/components/Header/Header.styles.js
  frontend/src/views/HomePage/components/FeedArea/FeedArea.js
  frontend/src/views/HomePage/components/FeedArea/FeedArea.styles.js
  frontend/src/views/HomePage/components/UploadImage/UploadImage.js
  frontend/src/views/HomePage/components/UploadImage/UploadImage.styles.js
Labels: size/L, lgtm, ⚙️ refactor/QOL

#137 Provide language review suggestions
  README.md
  docs/README.md
  docs/architecture.md
  docs/details.md
  docs/development.md
Labels: documentation, size/L, lgtm

#134 Add wrapper for error handling
  backend/go.mod
  backend/go.sum
  backend/internal/api/handler.go
  backend/internal/api/handler_test.go
  backend/internal/database/database.go
  backend/internal/database/database_test.go
  backend/internal/events/event.go
  backend/internal/events/event_test.go
Labels: size/L, lgtm, ⚙️ refactor/QOL

#139 Language and form suggestions
  README.md
  docs/architecture.md
  docs/assets/diagram_showcase.svg
  docs/development.md
Labels: documentation, size/S, lgtm

#140 Clean code
  frontend/src/views/HomePage/components/UploadImage/UploadImage.js
Labels: size/XS, lgtm, ✨ hotfix ✨

#142 Displaying landmark map
  frontend/src/API.js
  frontend/src/views/ImageDetailsPage/components/FeatureTiles/LandmarksMapTile/LandmarksMapTile.js
  frontend/src/views/ImageDetailsPage/components/ImageDetails/ImageDetails.js
  resources/frontend/frontend-config.yaml
Labels: enhancement, size/M, lgtm

#147 Dev guide update
  README.md
  docs/details.md
  docs/development.md
Labels: size/S, lgtm

#148 Update renaming
  frontend/src/views/ImageDetailsPage/components/FeatureTiles/TextDocSentimentTile/TextDocSentimentTile.js
  frontend/src/views/ImageDetailsPage/components/FeatureTiles/TextSentenceSentimentTile/TextSentenceSentimentTile.js
Labels: size/XS, lgtm, ✨ hotfix ✨

#145 NSFW filter
  frontend/src/views/ImageDetailsPage/ImageDetailsPage.js
  frontend/src/views/ImageDetailsPage/components/ImageDetails/ImageDetails.js
  frontend/src/views/ImageDetailsPage/components/ImageDetailsArea/ImageDetailsArea.js
  frontend/src/views/ImageDetailsPage/components/ImageDetailsArea/ImageDetailsArea.styles.js
  resources/functions/nsfw.yaml
  resources/subscriptions/nsfw-sub.yaml
Labels: enhancement, size/L, lgtm

#150 Repair / and sentece bug
  frontend/src/views/ImageDetailsPage/components/ImageDetails/ImageDetails.js
  resources/functions/text-category.yaml
Labels: bug, size/XS, lgtm, ✨ hotfix ✨

#154 Fixed text-sentiment
  frontend/src/views/ImageDetailsPage/components/ImageDetails/ImageDetails.js
  resources/functions/text-sentiment.yaml
Labels: bug, size/S, lgtm, ✨ hotfix ✨

#153 Implementation of zap logger
  backend/cmd/main.go
  backend/go.mod
  backend/go.sum
  backend/internal/api/handler.go
  backend/internal/api/handler_test.go
  backend/internal/database/database.go
  backend/internal/database/database_test.go
  backend/internal/logging/logging.go
  resources/backend/deployment.yaml
Labels: size/L, lgtm, ⚙️ refactor/QOL

#155 Diagram Update
  README.md
  docs/architecture.md
  docs/assets/diagram_showcase.svg
Labels: documentation, size/XS, lgtm, ✨ hotfix ✨

#156 New UI for Details Page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/styles/style.js
  frontend/src/assets/styles/theme.js
  frontend/src/views/ImageDetailsPage/components/FeatureTiles/FaceTile/FaceTile.js
  frontend/src/views/ImageDetailsPage/components/FeatureTiles/FeatureTile/FeatureTile.js
  frontend/src/views/ImageDetailsPage/components/FeatureTiles/LandmarksMapTile/LandmarksMapTile.js
  frontend/src/views/ImageDetailsPage/components/FeatureTiles/LandmarksTile/LandmarksTile.js
  frontend/src/views/ImageDetailsPage/components/FeatureTiles/TextCategoryTile/TextCategoryTile.js
  frontend/src/views/ImageDetailsPage/components/FeatureTiles/TextDocSentimentTile/TextDocSentimentTile.js
  frontend/src/views/ImageDetailsPage/components/FeatureTiles/TextEntityTile/TextEntityTile.js
  frontend/src/views/ImageDetailsPage/components/FeatureTiles/TextSentenceSentimentTile/TextSentenceSentimentTile.js
  frontend/src/views/ImageDetailsPage/components/FeatureTiles/TextSentenceSentimentTile/TextSentenceSentimentTile.styles.js
  frontend/src/views/ImageDetailsPage/components/FeatureTiles/TextTile/TextTile.js
  frontend/src/views/ImageDetailsPage/components/FeatureTiles/TextTile/TextTile.styles.js
  frontend/src/views/ImageDetailsPage/components/ImageDetails/ImageDetails.js
  frontend/src/views/ImageDetailsPage/components/ImageDetails/ImageDetails.styles.js
  frontend/src/views/ImageDetailsPage/components/ImageDetailsArea/ImageDetailsArea.styles.js
Labels: enhancement, size/L, lgtm, ⚙️ refactor/QOL

#163 Update CODEOWNERS
  CODEOWNERS
Labels: documentation, size/XS, lgtm

#164 Readme edit
  README.md
Labels: size/XS, lgtm
