Repository kyma-incubator/kyma-showcase, pull requests merged in 2021-08, with the labels that each got.

#26 Dockerfile and nginx configuration
  frontend/.dockerignore
  frontend/Dockerfile
  frontend/nginx.conf
Labels: enhancement, lgtm, size/M

#27 Fetching images from fake API to homepage
  frontend/src/API.js
  frontend/src/App.js
  frontend/src/views/HomePage/components/ImageTile/ImageTile.js
  frontend/src/views/HomePage/components/ImagesSection/ImagesSection.js
  frontend/src/views/HomePage/components/UploadImage/UploadImage.js
Labels: enhancement, lgtm, size/M

#28 First integration with own backend
  backend/.gitignore
  backend/api.go
  backend/docker-compose.yml
  frontend/src/API.js
  frontend/src/App.js
  frontend/src/contexts/imagesContext.js
  frontend/src/views/HomePage/components/FeedArea/FeedArea.js
  frontend/src/views/HomePage/components/FeedArea/FeedArea.styles.js
  frontend/src/views/HomePage/components/ImageTile/ImageTile.js
  frontend/src/views/HomePage/components/ImagesSection/ImagesSection.js
  frontend/src/views/HomePage/components/ImagesSection/ImagesSection.styles.js
  frontend/src/views/HomePage/components/UploadImage/UploadImage.js
Labels: enhancement, size/L, lgtm

#29 Update README.md
  README.md
Labels: documentation, size/M, lgtm

#30 Integration with new API model
  frontend/src/API.js
  frontend/src/App.js
  frontend/src/contexts/imagesContext.js
  frontend/src/views/HomePage/HomePage.js
  frontend/src/views/HomePage/components/ImageTile/ImageTile.js
  frontend/src/views/HomePage/components/ImagesSection/ImagesSection.js
  frontend/src/views/HomePage/components/UploadImage/UploadImage.js
Labels: enhancement, size/M, lgtm

#32 Modifying styles to improve UI.
  frontend/src/assets/styles/style.js
  frontend/src/assets/styles/theme.js
  frontend/src/components/Footer/Footer.js
  frontend/src/components/Footer/Footer.styles.js
  frontend/src/views/HomePage/components/UploadImage/UploadImage.js
  frontend/src/views/HomePage/components/UploadImage/UploadImage.styles.js
Labels: enhancement, size/L, lgtm

#31 Generating unique ID for each picture
  backend/api.go
  backend/api_test.go
  backend/database_test.go
  backend/go.mod
  backend/go.sum
  backend/main.go
  backend/mocks/IdGenerator.go
  backend/model.go
  backend/request.http
  backend/utils.go
Labels: enhancement, size/XL, lgtm

#41 Fetch kubernetized API
  frontend/public/config/config.json
  frontend/src/API.js
  frontend/src/index.js
Labels: enhancement, size/M, lgtm

#40 Add Kubernetes resources
  resources/backend/deployment.yaml
  resources/backend/service.yaml
  resources/frontend/deployment.yaml
  resources/frontend/frontend-config.yaml
  resources/frontend/service.yaml
  resources/redis/deployment.yaml
  resources/redis/service.yaml
Labels: enhancement, size/L, lgtm

#44 Change dockerfile
  backend/Dockerfile
  backend/Makefile
Labels: size/S, lgtm

#45 Disable button fix
  frontend/src/assets/styles/style.js
  frontend/src/views/HomePage/components/UploadImage/UploadImage.js
  frontend/src/views/HomePage/components/UploadImage/UploadImage.styles.js
Labels: enhancement, size/S, lgtm

#47 ImageTile height fix
  frontend/src/views/HomePage/components/ImageTile/ImageTile.styles.js
Labels: enhancement, size/XS, lgtm

#48 Loading spinner
  frontend/src/views/HomePage/components/ImagesSection/ImagesSection.js
  frontend/src/views/HomePage/components/ImagesSection/ImagesSection.styles.js
  frontend/src/views/HomePage/components/UploadImage/UploadImage.js
Labels: enhancement, size/M, lgtm

#51 Move loader spinner to global style and change display state
  frontend/src/assets/styles/style.js
  frontend/src/views/HomePage/components/ImagesSection/ImagesSection.js
  frontend/src/views/HomePage/components/ImagesSection/ImagesSection.styles.js
Labels: enhancement, size/M, lgtm

#53 Readme update
  README.md
Labels: documentation, size/M, lgtm

#54 Updating yaml files
  resources/backend/apirule.yaml
  resources/backend/deployment.yaml
  resources/backend/service.yaml
  resources/frontend/apirule.yaml
  resources/frontend/deployment.yaml
  resources/frontend/frontend-config.yaml
  resources/frontend/service.yaml
  resources/redis/deployment.yaml
  resources/redis/service.yaml
Labels: enhancement, size/L, lgtm

#56 Modify nginx config
  frontend/nginx.conf
  frontend/src/App.js
Labels: enhancement, size/XS, lgtm, ✨ hotfix ✨

#57 Event type fix
  resources/backend/deployment.yaml
Labels: size/XS, lgtm, ✨ hotfix ✨

#68 Create lambda that send image to GCP
  resources/functions/image-process.yaml
Labels: enhancement, size/M, lgtm, 😡 friday PR 🤬

#69 Update README.md with GCP secrets information
  README.md
Labels: documentation, size/XS, lgtm

#52 Eventing functionality
  backend/cmd/main.go
  backend/docker-compose.yml
  backend/go.mod
  backend/go.sum
  backend/internal/api/api.go
  backend/internal/api/api_test.go
  backend/internal/api/idgenerator.go
  backend/internal/api/mocks/DBManager.go
  backend/internal/api/mocks/EventBus.go
  backend/internal/api/mocks/IdGenerator.go
  backend/internal/database/database.go
  backend/internal/events/event.go
  backend/internal/events/event_test.go
  backend/request.http
  resources/backend/deployment.yaml
Labels: enhancement, size/L, lgtm, 😡 friday PR 🤬

#74 Env fields configuration
  backend/cmd/main.go
  resources/backend/deployment.yaml
Labels: size/S, lgtm, ⚙️ refactor/QOL

#70 Image processing lambda
  resources/functions/image-get.yaml
  resources/functions/image-process.yaml
  resources/functions/image-processing.yaml
  resources/subscriptions/image-processing-subscription.yaml
Labels: enhancement, size/L, lgtm
